version: "3.8"

volumes:
  pg_volume:
  pg_test_volume:

services:
  go-auth:
    build:
      context: .
      dockerfile: go.local.Dockerfile
    networks:
      - banking-system
    depends_on:
      - pg
    volumes:
      - .:/app

  pg-auth:
    image: postgres:15-alpine3.18
    environment:
      - "POSTGRES_DB=${PG_DB_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pg_volume:/var/lib/postgresql/data
    networks:
      - banking-system

  pg-test-auth:
    image: postgres:15-alpine3.18
    environment:
      - "POSTGRES_DB=${PG_DB_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT_TEST}:5432"
    volumes:
      - pg_test_volume:/var/lib/postgresql/data
    networks:
      - banking-system

  redis-auth:
    image: redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - banking-system

  migrator-auth:
    build:
      context: .
      dockerfile: migration.Dockerfile
    restart: on-failure
    depends_on:
      - pg
      - pg-test
    networks:
      - banking-system

networks:
  banking-system:
    name: banking-system
    external: true
